### PR TITLE
Mention click more obviously in intro paragraph

### PR DESCRIPTION
**Pull request by bittner**
I felt the introductory paragraph of this project's README doesn't clearly explain what this project is about. This change should fix that.

**P.S.:** In addition, could you add a short description to the GitHub project (at the top of the GitHub project start page)? Thanks!

### CODE REVIEW

**Comment by bittner** [comment]
> So there is a lot for me to learn how to ...

Alright! The start by adding an avatar image in your GitHub profile! :laughing: 

Thanks for merging!

**Comment by bittner** [comment]
The "description" I referred to that you should add/update is the one that currently says, _"No description, website, or topics provided."_ on the [project home page](https://github.com/szsdk/quick).

Just edit it one the GitHub UI. You're (probably) the only one that can change it in your project.

**Comment by bittner** [comment]
Just a head up: I mentioned this project in https://github.com/chriskiehl/Gooey/issues/135.

**Comment by szsdk** [comment]
@bittner  Thanks for selling this project.

**Pull request merged**
